# Generated by Django 3.2.17 on 2023-02-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=None, upload_to='img'),
            preserve_default=False,
        ),
    ]
