# Generated by Django 4.0.6 on 2022-10-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='indexing_ap_name_f5b584_idx'),
        ),
    ]
