# Generated by Django 4.0.6 on 2022-10-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing_app', '0002_person_indexing_ap_name_f5b584_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('person', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
        ),
    ]
