# Generated by Django 4.0.6 on 2022-10-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexing_app', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexing_app.person'),
        ),
    ]
