# Generated by Django 4.1.6 on 2023-02-08 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item', models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('MOBILE', 'MOBILE')], default='LAPTOP', max_length=12)),
                ('is_laptop', models.CharField(choices=[('MAC', 'MAC'), ('WINDOW', 'WINDOW')], default='WINDOW', max_length=12)),
                ('is_mobile', models.CharField(choices=[('IPHONE', 'IPHONE'), ('ANDROID', 'ANDROID')], default='ANDROID', max_length=12)),
                ('title', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
