# Generated by Django 3.2.17 on 2023-02-20 05:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='is_laptop',
            field=models.CharField(choices=[('Mac', 'Mac'), ('Window', 'Window')], default='WINDOW', max_length=12),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='is_mobile',
            field=models.CharField(blank=True, choices=[('IPhone', 'IPhone'), ('Android', 'Android')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile')], max_length=20),
        ),
    ]
