# Generated by Django 4.1.6 on 2023-02-08 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('PARTIALACCEPTED', 'PARTIALACCEPTED')], default='PENDING', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('remaining_leaves', models.IntegerField()),
                ('attachments', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('approval_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeavesDetails',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('leave_type', models.CharField(choices=[('FULLDAY', 'FULLDAY'), ('HALFDDAY', 'HALFDAY'), ('SHORTLEAVE', 'SHORTLEAVE')], default='FULLDAY', max_length=10)),
                ('status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=12)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days', models.IntegerField()),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leaves.leaves')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
