# Generated by Django 3.2.17 on 2023-02-23 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0002_auto_20230221_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavesdetails',
            old_name='from_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leavesdetails',
            old_name='to_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='leaves',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaves',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaves',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaves',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
