# Generated by Django 3.2.17 on 2023-02-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_auto_20230223_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavesdetails',
            name='days',
        ),
        migrations.AddField(
            model_name='leaves',
            name='days',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaves',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Partiall Accepted', 'Partially Accepted')], default='Pending', max_length=20),
        ),
    ]
