# Generated by Django 3.2.17 on 2023-02-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_auto_20230223_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='start_time',
        ),
    ]
