# Generated by Django 3.2.17 on 2023-03-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_auto_20230223_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='remaining_leaves',
            field=models.FloatField(),
        ),
    ]
