# Generated by Django 4.0.6 on 2022-10-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_app', '0003_rename_user_name_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
