# Generated by Django 4.0.6 on 2022-10-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_app', '0004_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_super_user',
            field=models.BooleanField(default=False),
        ),
    ]
