# Generated by Django 4.0.6 on 2022-10-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_app', '0008_rename_is_super_user_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
    ]
